filebeat.prospectors:

- input_type: log

  paths:
    - /home/vagrant/dpa/logs/*.log

  fields:
    beat_id: "prd_dpa"

  fields_under_root: true


exclude_lines: ["DEBUG"]


output.logstash:
  hosts: ["192.168.50.4:5044"]

output.file:

  path: /tmp

  filename: filebeatout

logging.to_files: true
logging.files:
  path: /tmp

  name: mybeatlog
