# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Note:  This is not the officially recommended box!  See https://www.vagrantup.com/docs/boxes.html
  config.vm.box = "ubuntu/trusty64"
  # Initial experiments with xenial64 showed that the image is not completely ready yet.
  # config.vm.box = "ubuntu/xenial64"

  config.vm.provision :shell, :name => "bootstrap.sh", :path => "bootstrap.sh"
  # Tomcat med DOMS + Central Web-service.
  config.vm.network :forwarded_port, :host => 7880, :guest => 7880
  # Java debug port (easy with Tomcat)
  config.vm.network :forwarded_port, :host => 8000, :guest => 8000
  # Postgresql network port, high end to avoid clash with host install
  config.vm.network :forwarded_port, :host => 15432, :guest => 5432
  # DOMS Wui Tomcat port
  config.vm.network :forwarded_port, :host => 58708, :guest => 58708
  # SBOI Tomcat port
  config.vm.network :forwarded_port, :host => 58608, :guest => 58608
  # Zookeeper lock server
  config.vm.network :forwarded_port, :host => 2181, :guest => 2181
  # Bitrepository_stub file server
  config.vm.network :forwarded_port, :host => 58709, :guest => 58709

  # ActiveMQ port
  config.vm.network :forwarded_port, :host => 61616, :guest => 61616

  # Bit repository web client port
  config.vm.network :forwarded_port, :host => 18080, :guest => 8080



  # Be able to get the artifacts from host Maven build.
  config.vm.synced_folder "../../target/", "/target"
  config.vm.synced_folder "../../../../delivery-samples/", "/delivery-samples"

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 2 # or more for heavy load
  end

  # for jvisualvm
  config.ssh.forward_x11 = true

  # These network things are nessesary to make ubuntu work fast
  # TODO: Insert links to Stackoverflow questions, and explain why!
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end
  config.vm.network :public_network, :nictype => 'virtio', :type => "dhcp", :use_dhcp_assigned_default_route => true

    # Easier naming disabled until we have a ruby snippet adding the CWD to the name.
#  config.vm.provider :virtualbox do |v|
#    v.name = "doms-vagrant-testbed-2"
#  end

  # For bash prompt when running along DOMS Gui-installer vagrant.
  config.vm.hostname = "doms-vagrant-testbed"
  # For shared virtual network when running along DOMS Gui-installer vagrant.
  config.vm.network :private_network, :ip => "192.168.50.2", :virtualbox__intnet => "localvagrantnetwork"


  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end
end
