package org.statsbiblioteket.digital_pligtaflevering_aviser.ui.datamodel;


import java.util.HashMap;
import java.util.LinkedHashMap;

public class DeliveryPattern {


    public static HashMap<String, LinkedHashMap<String, Boolean>> deliveryPatterns = new HashMap<String, LinkedHashMap<String, Boolean>>() {
        {
            put("aarhusstiftstidende",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("arbejderen",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.FALSE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.FALSE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("berlingsketidende",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("boersen",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.FALSE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("bornholmstidende",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("bt",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("dagbladetkoege",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("dagbladetringsted",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("dagbladetroskilde",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("dagbladetstruer",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("dernordschleswiger",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("ekstrabladet",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("flensborgavis",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("fredericiadagblad1890",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("frederiksborgamtsavis",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("fyensstiftstidende",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("fynsamtsavissvendborg",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("helsingoerdagblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("herningfolkeblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("holstebrodagblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("horsensfolkeblad1866",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("information",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("jydskevestkystensoenderborg",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("jydskevestkystenbillund",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("jydskevestkystenvarde",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("jydskevestkystenesbjerg",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("jydskevestkystenhaderslev",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("jydskevestkystenkolding1995",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("jydskevestkystentoender",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("jydskevestkystenaabenraa",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("jydskevestkystenvejen",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("kristeligtdagblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("lemvigfolkeblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("licitationen",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("lollandfalstersfolketidende",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("metroxpressoest",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.FALSE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("metroxpressvest",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.FALSE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("midtjyllandsavis1857",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("morgenavisenjyllandsposten",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("morsoefolkeblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("nordjyskestiftstidendeaalborg",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("nordjyskestiftstidendehimmerland",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("nordjyskestiftstidendevendsyssel",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("nordvestnytholbaek",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("nordvestnytkalundborg",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("politiken",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("politikenweekly",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.FALSE);
                            put("Tue",Boolean.FALSE);
                            put("Wed",Boolean.FALSE);
                            put("Thu",Boolean.FALSE);
                            put("Fri",Boolean.FALSE);
                            put("Sat",Boolean.FALSE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("randersamtsavis",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("ringkjoebingamtsdagblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("sjaellandskenaestved",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("sjaellandskeslagelse",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("skivefolkeblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("thisteddagblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.TRUE);
                        }
                    });
            put("vejleamtsfolkeblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("viborgstiftsfolkeblad",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.TRUE);
                            put("Tue",Boolean.TRUE);
                            put("Wed",Boolean.TRUE);
                            put("Thu",Boolean.TRUE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.TRUE);
                            put("Sun",Boolean.FALSE);
                        }
                    });
            put("weekendavisen",
                    new LinkedHashMap<String, Boolean>() {
                        {
                            put("Mon",Boolean.FALSE);
                            put("Tue",Boolean.FALSE);
                            put("Wed",Boolean.FALSE);
                            put("Thu",Boolean.FALSE);
                            put("Fri",Boolean.TRUE);
                            put("Sat",Boolean.FALSE);
                            put("Sun",Boolean.FALSE);
                        }
                    });

        }
    };
}
